# Generated by Django 3.0.8 on 2020-07-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='numero',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
