# Generated by Django 3.0.8 on 2020-10-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_prestation'),
        ('core', '0014_auto_20201008_1556'),
    ]

    operations = [
    ]
