# Generated by Django 3.0.8 on 2020-10-15 21:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20201011_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Adresse'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
