# Generated by Django 3.0.8 on 2020-10-19 21:32

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_parametrescompte_nom_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrescompte',
            name='nom_footer',
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='footer',
            field=models.ImageField(blank=True, max_length=128, null=True, upload_to=apps.core.models.footer_storage_path),
        ),
    ]
