# Generated by Django 3.0.8 on 2020-10-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_certificat_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nouveau',
            field=models.BooleanField(default=True),
        ),
    ]
