# Generated by Django 3.0.8 on 2020-11-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201106_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reglement',
            old_name='Admission',
            new_name='admission',
        ),
    ]
