# Generated by Django 3.0.8 on 2020-11-19 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20201118_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationcolposcopie',
            old_name='conculsion',
            new_name='conculsions',
        ),
    ]
