# Generated by Django 3.0.8 on 2020-11-19 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20201119_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationcolposcopie',
            old_name='conculsions',
            new_name='conclusion',
        ),
    ]
