# Generated by Django 3.0.8 on 2020-12-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_reglement_date_creation'),
        ('core', '0054_consultationecho11sa_consultationobstetrique'),
    ]

    operations = [
    ]
