# Generated by Django 3.0.8 on 2020-12-26 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_merge_20201226_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationechocroissance',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lignereglement',
            name='reglement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Reglement'),
        ),
    ]
