# Generated by Django 3.0.8 on 2021-01-20 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_imageconsultation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageconsultation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 22, 31, 0, 198335)),
            preserve_default=False,
        ),
    ]
