# Generated by Django 3.0.8 on 2021-01-25 22:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_imageconsultation_impression'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='h_deb_am_jeudi',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_deb_am_lundi',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_deb_am_mardi',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_deb_am_mercredi',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_deb_am_samedi',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_deb_am_vendredi',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_deb_mat_jeudi',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_deb_mat_lundi',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_deb_mat_mardi',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_deb_mat_mercredi',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_deb_mat_samedi',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_deb_mat_vendredi',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_fin_am_jeudi',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_fin_am_lundi',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_fin_am_mardi',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_fin_am_mercredi',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_fin_am_samedi',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_fin_am_vendredi',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_fin_mat_jeudi',
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_fin_mat_lundi',
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_fin_mat_mardi',
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_fin_mat_mercredi',
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_fin_mat_samedi',
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='h_fin_mat_vendredi',
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
        migrations.CreateModel(
            name='AbsenceMedecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('praticien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Medecin')),
            ],
        ),
    ]
