# Generated by Django 3.0.8 on 2021-03-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_consultationechopelvienne_adenomyose_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='listechoix',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
