# Generated by Django 3.0.8 on 2021-04-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20210406_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='praticiens_correspondants',
            field=models.ManyToManyField(blank=True, to='core.Praticien'),
        ),
    ]
