# Generated by Django 3.0.8 on 2021-04-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_auto_20210421_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativepma',
            name='reussie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suivitraitementpma',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suivitraitementpma',
            name='traitments_valeurs',
            field=models.ManyToManyField(blank=True, through='core.TraitementValeurPMA', to='core.TraitementPMA'),
        ),
    ]
