# Generated by Django 3.0.8 on 2021-04-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_auto_20210422_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativepma',
            name='commentaires',
            field=models.TextField(blank=True, null=True),
        ),
    ]
