# Generated by Django 3.0.8 on 2021-04-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_auto_20210428_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myome',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Consultation'),
        ),
    ]
