# Generated by Django 3.0.8 on 2021-05-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_resultatanalysebiologique_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencemedecin',
            name='motif',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
