# Generated by Django 3.0.8 on 2021-05-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_auto_20210510_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ancien_numero',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
