# Generated by Django 3.0.8 on 2021-05-28 23:03

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_auto_20210512_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysebiologique',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reglement',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterField(
            model_name='collectionanalysebiologique',
            name='analyses',
            field=apps.core.models.AnalyseOrderedManyToManyField(to='core.AnalyseBiologique'),
        ),
    ]
