# Generated by Django 3.0.8 on 2021-06-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_auto_20210622_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesuresPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField()),
                ('ta', models.CharField(blank=True, max_length=256, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('gly', models.CharField(blank=True, max_length=256, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
