# Generated by Django 3.0.8 on 2021-06-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_auto_20210623_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysebiologique',
            name='ordre',
            field=models.SmallIntegerField(default=1000),
        ),
    ]
