# Generated by Django 3.0.8 on 2021-06-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_auto_20210627_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationgynecologique',
            name='profession_conjoint',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='interrogatoirepma',
            name='profession_conjoint',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession_conjoint',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
