# Generated by Django 3.0.8 on 2021-06-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_auto_20210627_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='praticien',
            name='titre',
            field=models.CharField(choices=[('Dr', 'Docteur'), ('Pr', 'Professeur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle'), ('Mr', 'Monsieur')], default='Dr', max_length=8),
        ),
    ]
