# Generated by Django 3.0.8 on 2021-08-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_auto_20210814_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='telephone_autre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
