# Generated by Django 3.0.8 on 2021-09-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_srconsultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationechopelvienne',
            name='ovaire_droit_follicules_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationechopelvienne',
            name='ovaire_gauche_follicules_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_droit_follicules_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_follicules_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
