# Generated by Django 3.0.8 on 2021-10-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_grossesse_aspegic'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationobstetrique',
            name='echo_t3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
