# Generated by Django 3.0.8 on 2021-10-23 09:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_antecedentobstetrique_honoraires'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='modele_attestation_grossesse',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='modele_lettre_fittofly',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
