# Generated by Django 3.0.8 on 2021-10-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_auto_20211023_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationgynecologique',
            name='motif_autre',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='type',
            field=models.CharField(choices=[('certificat_medical', 'Certificat médical'), ('certificat_presence', 'Certificat médical de présence'), ('lettre_accouchement', "Lettre d'accouchement"), ('lettre_confidentielle', 'Lettre confidentielle'), ('attestation_grossesse', 'Attestation de grossesse'), ('lettre_fittofly', 'Certificat médical Fit To Fly')], default='certificat_medical', max_length=128),
        ),
    ]
