# Generated by Django 3.0.8 on 2021-12-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_admission_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='ajouter_date_courriers',
            field=models.BooleanField(default=True),
        ),
    ]
