# Generated by Django 3.0.8 on 2022-01-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_listechoix_normale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grossesse',
            name='nb_foetus',
            field=models.CharField(blank=True, choices=[('', ''), ('unique', 'Unique'), ('gemellaire', 'Gémellaire'), ('triple', 'Triple')], default='unique', max_length=256, null=True),
        ),
    ]
