# Generated by Django 3.0.8 on 2022-02-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_auto_20220204_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglement',
            name='mutuelle',
            field=models.BooleanField(default=False),
        ),
    ]
