# Generated by Django 4.0.6 on 2022-12-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_alter_consultationechopelvienne_adenomyose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motifconsultation',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
