# Generated by Django 4.0.6 on 2026-03-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0203_mesures_consultation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='admission',
            name='core_admission_patient_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='consultation',
            name='core_consultation_patient_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='rdv',
            name='core_rdv_compte_debut_idx',
        ),
        migrations.RemoveIndex(
            model_name='rdv',
            name='core_rdv_compte_ancien_debut_idx',
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['patient', 'date'], name='core_admiss_patient_faa7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', 'date'], name='core_consul_patient_38bde2_idx'),
        ),
        migrations.AddIndex(
            model_name='rdv',
            index=models.Index(fields=['compte', 'debut'], name='core_rdv_compte__934825_idx'),
        ),
        migrations.AddIndex(
            model_name='rdv',
            index=models.Index(fields=['compte', 'ancien_debut'], name='core_rdv_compte__4aaa0f_idx'),
        ),
    ]
