# Generated by Django 3.0.8 on 2020-09-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200824_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='antecedents_familiaux_defaut',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='antecedents_gynecologiques_defaut',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='antecedents_medico_chirurgicaux_defaut',
            field=models.TextField(blank=True, null=True),
        ),
    ]
