# Generated by Django 3.0.8 on 2020-09-17 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ordonnance_prescription_traitement'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traitement',
            name='compte',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.Compte'),
            preserve_default=False,
        ),
    ]
