# Generated by Django 3.0.8 on 2020-09-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200917_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='date',
            field=models.DateField(),
        ),
    ]
