# Generated by Django 3.0.8 on 2020-09-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_patient_lieu_accouchement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieuaccouchement',
            name='adresse',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
