# Generated by Django 3.0.8 on 2020-10-24 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20201011_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('espece_payment', models.FloatField(blank=True, null=True)),
                ('cheque_payment', models.FloatField(blank=True, null=True)),
                ('cb_payment', models.FloatField(blank=True, null=True)),
                ('cheque_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('titulaire', models.CharField(blank=True, max_length=128, null=True)),
                ('date_cheque', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
                ('praticien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Medecin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
