# Generated by Django 3.0.8 on 2020-10-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201013_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='nom_footer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
