# Generated by Django 3.0.8 on 2020-10-31 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20201025_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglement',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='reglement',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='reglement',
            name='mutuelle',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='LigneReglement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestation', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('prix_ttc', models.FloatField(blank=True, null=True)),
                ('reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Reglement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
