# Generated by Django 3.0.8 on 2020-11-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201108_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Reglement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
