# Generated by Django 3.0.8 on 2020-10-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201030_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='categorie',
            field=models.CharField(choices=[('biologie', 'Biologie'), ('examen_complementaire', 'Examen complémentaire')], default='', max_length=256),
        ),
    ]
