# Generated by Django 3.0.8 on 2020-11-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cloture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignereglement',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lignereglement',
            name='prestation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lignereglement',
            name='reglement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Reglement'),
        ),
    ]
