# Generated by Django 3.0.8 on 2020-11-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20201101_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeChoix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulaire', models.CharField(max_length=256)),
                ('champ', models.CharField(max_length=256)),
                ('valeur', models.CharField(max_length=256)),
            ],
        ),
    ]
