# Generated by Django 3.0.8 on 2020-11-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20201104_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationGynecologique',
            fields=[
                ('consultation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Consultation')),
                ('ddr', models.DateField(blank=True, null=True)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('endometriose', models.BooleanField(blank=True, null=True)),
                ('ths', models.BooleanField(blank=True, null=True)),
                ('signe_clinique', models.BooleanField(blank=True, null=True)),
                ('commentaire_contraception', models.CharField(blank=True, max_length=512, null=True)),
                ('dyspareunies', models.BooleanField(blank=True, null=True)),
                ('incontinence', models.BooleanField(blank=True, null=True)),
                ('sensation_pesanteur', models.BooleanField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('ta', models.CharField(blank=True, max_length=256, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('alb', models.CharField(blank=True, max_length=256, null=True)),
                ('gly', models.CharField(blank=True, max_length=256, null=True)),
                ('commentaires_cliniques', models.TextField(blank=True, null=True)),
                ('prochaine_consultation_date', models.DateField(blank=True, null=True)),
                ('prochaine_consultation_approx', models.CharField(blank=True, max_length=128, null=True)),
                ('examens', models.TextField(blank=True, null=True)),
                ('traitements', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('abondance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abondance', to='core.ListeChoix')),
                ('cycles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles', to='core.ListeChoix')),
                ('douleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='douleur', to='core.ListeChoix')),
                ('effets_indesirables', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effets_indesirables', to='core.ListeChoix')),
                ('examen_sous_speculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examen_sous_speculum', to='core.ListeChoix')),
                ('leuco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leuco', to='core.ListeChoix')),
                ('mode_contraception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mode_contraception', to='core.ListeChoix')),
                ('motif_consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motif_consultation', to='core.ListeChoix')),
                ('observance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observance', to='core.ListeChoix')),
                ('partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partenaire', to='core.ListeChoix')),
                ('seins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seins', to='core.ListeChoix')),
                ('syndrome_premenstruel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syndrome_premenstruel', to='core.ListeChoix')),
                ('tv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tv', to='core.ListeChoix')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.consultation',),
        ),
    ]
