# Generated by Django 3.0.8 on 2020-11-13 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_consultationgynecologique'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationgynecologique',
            name='satisfaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfaction', to='core.ListeChoix'),
        ),
    ]
