# Generated by Django 3.0.8 on 2020-11-18 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_consultationgynecologique_satisfaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
