# Generated by Django 3.0.8 on 2020-11-24 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20201117_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignereglement',
            name='reglement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ligne_reglement', to='core.Reglement'),
        ),
    ]
