# Generated by Django 3.0.8 on 2020-11-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20201127_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grossesse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_conjoint', models.CharField(blank=True, max_length=256, null=True)),
                ('prenom_conjoint', models.CharField(blank=True, max_length=256, null=True)),
                ('date_naissance_conjoint', models.DateField(blank=True, null=True)),
                ('telephone_conjoint', models.CharField(blank=True, max_length=20, null=True)),
                ('groupe_sanguin_conjoint', models.CharField(blank=True, choices=[('A-', 'A négatif'), ('A+', 'A positif'), ('B-', 'B négatif'), ('B+', 'B positif'), ('AB-', 'AB négatif'), ('AB+', 'AB positif'), ('O-', 'O négatif'), ('O+', 'O positif')], max_length=3, null=True)),
                ('consanguinite_conjoint', models.CharField(choices=[('cousin', 'Cousin')], default='', max_length=256)),
                ('etat_sante_conjoint', models.TextField(blank=True, null=True)),
                ('poids_avant_grossesse', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('ddr', models.DateField(blank=True, null=True)),
                ('ddg_corrige', models.DateField(blank=True, null=True)),
                ('cycle', models.IntegerField(default=28)),
                ('donnee_grossesse', models.CharField(choices=[('unique', 'Unique'), ('gemellaire', 'Gémellaire'), ('triple', 'Triple')], default='', max_length=256)),
                ('conception', models.CharField(choices=[('spontannee', 'Spontannée'), ('iac', 'IAC'), ('fiv', 'FIV')], default='', max_length=256)),
                ('date_echo', models.DateField(blank=True, null=True)),
                ('lcc_1', models.FloatField(blank=True, null=True)),
                ('lcc_2', models.FloatField(blank=True, null=True)),
                ('cn_1', models.FloatField(blank=True, null=True)),
                ('cn_2', models.FloatField(blank=True, null=True)),
                ('score_herman_1', models.FloatField(blank=True, null=True)),
                ('score_herman_2', models.FloatField(blank=True, null=True)),
                ('tabac', models.BooleanField(blank=True, null=True)),
                ('listeria', models.BooleanField(blank=True, null=True)),
                ('toxoplasmose', models.BooleanField(blank=True, null=True)),
                ('cmv', models.BooleanField(blank=True, null=True)),
                ('alcool', models.BooleanField(blank=True, null=True)),
                ('epp', models.BooleanField(blank=True, null=True)),
                ('ppo', models.BooleanField(blank=True, null=True)),
                ('adp', models.BooleanField(blank=True, null=True)),
                ('allaitement_maternel', models.BooleanField(blank=True, null=True)),
                ('allaitement_artificiel', models.BooleanField(blank=True, null=True)),
                ('infos_complemenatires', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
