# Generated by Django 3.0.8 on 2020-11-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_grossesse_type_grossesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='encours',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Patient'),
            preserve_default=False,
        ),
    ]
