# Generated by Django 3.0.8 on 2020-11-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20201129_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grossesse',
            name='score_herman_1',
            field=models.CharField(blank=True, choices=[('', ''), ('cn_non_connue', 'CN non connue'), ('cn_non_mesuree', 'CN non mesurée'), ('cn_non_significative', 'CN non significative pour cette LCC'), ('score_9', 'Score de Herman 9'), ('score_4', 'Score de Herman < 4')], default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='score_herman_2',
            field=models.CharField(blank=True, choices=[('', ''), ('cn_non_connue', 'CN non connue'), ('cn_non_mesuree', 'CN non mesurée'), ('cn_non_significative', 'CN non significative pour cette LCC'), ('score_9', 'Score de Herman 9'), ('score_4', 'Score de Herman < 4')], default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='score_herman_3',
            field=models.CharField(blank=True, choices=[('', ''), ('cn_non_connue', 'CN non connue'), ('cn_non_mesuree', 'CN non mesurée'), ('cn_non_significative', 'CN non significative pour cette LCC'), ('score_9', 'Score de Herman 9'), ('score_4', 'Score de Herman < 4')], default='', max_length=256, null=True),
        ),
    ]
