# Generated by Django 3.0.8 on 2020-12-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20201124_2335'),
        ('core', '0054_consultationecho11sa_consultationobstetrique'),
    ]

    operations = [
    ]
