# Generated by Django 3.0.8 on 2020-12-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20201226_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneesfoetus',
            name='cn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donneesfoetus',
            name='dat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donneesfoetus',
            name='lcc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
