# Generated by Django 3.0.8 on 2021-01-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20210103_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='lieu_accouchement_principal',
            field=models.CharField(blank=True, choices=[('D', 'Domicile'), ('H', 'Hôpital'), ('C', 'Clinique')], max_length=1),
        ),
    ]
