# Generated by Django 3.0.8 on 2021-01-12 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_antecedentobstetrique_lieu_accouchement_principal'),
        ('core', '0065_merge_20201228_2207'),
    ]

    operations = [
    ]
