# Generated by Django 3.0.8 on 2021-01-20 22:12

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20210120_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.models.repertoire_images_utilisateur)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Consultation')),
            ],
        ),
    ]
