# Generated by Django 3.0.8 on 2021-01-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_imageconsultation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageconsultation',
            name='impression',
            field=models.BooleanField(default=False),
        ),
    ]
