# Generated by Django 3.0.8 on 2021-01-28 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20210125_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseBiologique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('text', 'Texte'), ('number', 'Numérique')], max_length=32)),
                ('unite', models.CharField(default='', max_length=32)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Compte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionAnalyseBiologique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescription', models.DateTimeField()),
                ('date_resultat', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='rdv',
            options={'ordering': ['-debut']},
        ),
        migrations.CreateModel(
            name='ResultatAnalyseBiologique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('valeur', models.CharField(max_length=256)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AnalyseBiologique')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PrescriptionAnalyseBiologique')),
            ],
        ),
        migrations.AddField(
            model_name='prescriptionanalysebiologique',
            name='analyses',
            field=models.ManyToManyField(through='core.ResultatAnalyseBiologique', to='core.AnalyseBiologique'),
        ),
        migrations.AddField(
            model_name='prescriptionanalysebiologique',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient'),
        ),
        migrations.CreateModel(
            name='CollectionAnalyseBiologique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('analyses', models.ManyToManyField(to='core.AnalyseBiologique')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Compte')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
