# Generated by Django 3.0.8 on 2021-02-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20210207_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='lieu_accouchement_libre',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='antecedentobstetrique',
            name='lieu_accouchement_principal',
            field=models.CharField(blank=True, choices=[('D', 'Domicile'), ('H', 'Hôpital'), ('C', 'Clinique'), ('A', 'Autre')], max_length=1),
        ),
    ]
