# Generated by Django 3.0.8 on 2021-02-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20210207_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='lieu_accouchement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Etablissement'),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='lieu_accouchement_libre',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='lieu_accouchement_principal',
            field=models.CharField(blank=True, choices=[('D', 'Domicile'), ('H', 'Hôpital'), ('C', 'Clinique'), ('A', 'Autre')], max_length=1),
        ),
    ]
