# Generated by Django 3.0.8 on 2021-02-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20210210_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationechopelvienne',
            name='endometre_epaisseur',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
