# Generated by Django 3.0.8 on 2021-02-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_consultationechopelvienne_endometre_epaisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationgynecologique',
            name='leuco',
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='leuco',
            field=models.ManyToManyField(blank=True, null=True, related_name='leuco', to='core.ListeChoix'),
        ),
    ]
