# Generated by Django 3.0.8 on 2021-02-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_device_worklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='leuco',
            field=models.ManyToManyField(blank=True, related_name='leuco', to='core.ListeChoix'),
        ),
    ]
