# Generated by Django 3.0.8 on 2021-02-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20210223_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worklistitem',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Consultation'),
        ),
    ]
