# Generated by Django 3.0.8 on 2021-02-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20210224_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='listechoix',
            name='libelle',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listechoix',
            name='valeur',
            field=models.TextField(blank=True),
        ),
    ]
