# Generated by Django 3.0.8 on 2021-02-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20210225_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='distribution',
            field=models.CharField(choices=[('gyneco', 'Gynecologie'), ('cardio', 'Cardiologie'), ('general', 'Generaliste')], default='gyneco', max_length=128),
        ),
    ]
