# Generated by Django 3.0.8 on 2021-03-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_patient_antecedents_cardio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistitem',
            name='study_instance_uid',
            field=models.CharField(max_length=256),
        ),
    ]
