# Generated by Django 3.0.8 on 2021-03-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_auto_20210302_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=256)),
                ('contenu', models.TextField(blank=True)),
                ('categorie_consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_consultation', to='core.ListeChoix')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Compte')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
