# Generated by Django 3.0.8 on 2021-03-09 21:34

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_auto_20210305_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationechopelvienne',
            name='adenomyose',
        ),
        migrations.AddField(
            model_name='consultationechopelvienne',
            name='adenomyose',
            field=models.ManyToManyField(blank=True, related_name='adenomyose', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='imageconsultation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.models.upload_repertoire_images_utilisateur),
        ),
    ]
