# Generated by Django 3.0.8 on 2021-03-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_auto_20210326_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationobstetrique',
            name='alb',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='consultationobstetrique',
            name='commentaires_cliniques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationobstetrique',
            name='examen_sous_speculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_examen_sous_speculum', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationobstetrique',
            name='gly',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='consultationobstetrique',
            name='leuco',
            field=models.ManyToManyField(blank=True, related_name='obs_leuco', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationobstetrique',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationobstetrique',
            name='seins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_seins', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationobstetrique',
            name='ta',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='consultationobstetrique',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationobstetrique',
            name='tv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_tv', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='consanguinite_conjoint',
            field=models.CharField(blank=True, choices=[('', ''), ('oui', 'Oui'), ('non', 'Non')], default='', max_length=256, null=True),
        ),
    ]
