# Generated by Django 3.0.8 on 2021-04-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_auto_20210331_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysebiologique',
            name='modele_resultat',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
