# Generated by Django 3.0.8 on 2021-04-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_analysebiologique_modele_resultat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultatanalysebiologique',
            name='valeur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
