# Generated by Django 3.0.8 on 2021-04-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_auto_20210412_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='ddr_corrige',
            field=models.DateField(blank=True, null=True),
        ),
    ]
