# Generated by Django 3.0.8 on 2021-04-22 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_traitementvaleurpma_rang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traitementvaleurpma',
            options={'ordering': ['rang']},
        ),
        migrations.AlterField(
            model_name='traitementvaleurpma',
            name='traitement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.TraitementPMA'),
        ),
    ]
