# Generated by Django 3.0.8 on 2021-04-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_auto_20210428_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationgynecologique',
            name='adenomyose',
            field=models.ManyToManyField(blank=True, related_name='core_consultationgynecologique_adenomyose', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='adenomyose_conclusion',
            field=models.ManyToManyField(blank=True, related_name='core_consultationgynecologique_adenomyose_conclusion', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='anomalies_dispositif_intra_uterin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_anomalies_dispositif_intra_uterin', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='asymetrie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_asymetrie', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='cavite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_cavite', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='col_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_col_aspect', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='col_longueur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='col_vascularisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_col_vascularisation', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='commentaire_col_endometre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='commentaires_myometre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='cul_de_sac_latero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_cul_de_sac_latero', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='dispositif_intra_tubaire',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='endometre_echogenicite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_endometre_echogenicite', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='endometre_epaisseur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='endometre_visualisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_endometre_visualisation', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='hauteur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='hysterometrie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='largeur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='largeur_interostiale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='lateralisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_lateralisation', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ligne_cavitaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_ligne_cavitaire', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='localisation_dispositif_intra_uterin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_localisation_dispositif_intra_uterin', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='longueur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='longueur_totale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='malformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_malformation', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_mobilite', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_droit_accessibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_ovaire_droit_accessibilite', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_droit_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_ovaire_droit_aspect', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_droit_commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_droit_follicules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_ovaire_droit_follicules', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_droit_hauteur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_droit_largeur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_droit_longueur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_droit_mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_ovaire_droit_mobilite', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_droit_visibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_ovaire_droit_visibilite', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_droit_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_accessibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_ovaire_gauche_accessibilite', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_ovaire_gauche_aspect', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_follicules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_ovaire_gauche_follicules', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_hauteur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_largeur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_longueur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_ovaire_gauche_mobilite', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_visibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_ovaire_gauche_visibilite', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='paroi_anterieure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='paroi_posterieure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='position_uterus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_position_uterus', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='structures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_structures', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='titre_echo_pelvienne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_titre_echo_pelvienne', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='type_dispositif_intra_uterin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_type_dispositif_intra_uterin', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='volume_uterin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='volume_uterin_commentaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationgynecologique_volume_uterin_commentaire', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='adenomyose',
            field=models.ManyToManyField(blank=True, related_name='core_consultationechopelvienne_adenomyose', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='adenomyose_conclusion',
            field=models.ManyToManyField(blank=True, related_name='core_consultationechopelvienne_adenomyose_conclusion', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='anomalies_dispositif_intra_uterin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_anomalies_dispositif_intra_uterin', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='asymetrie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_asymetrie', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='cavite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_cavite', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='col_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_col_aspect', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='col_vascularisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_col_vascularisation', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='cul_de_sac_latero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_cul_de_sac_latero', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='endometre_echogenicite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_endometre_echogenicite', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='endometre_visualisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_endometre_visualisation', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='lateralisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_lateralisation', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ligne_cavitaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_ligne_cavitaire', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='localisation_dispositif_intra_uterin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_localisation_dispositif_intra_uterin', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='malformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_malformation', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_mobilite', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_droit_accessibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_ovaire_droit_accessibilite', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_droit_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_ovaire_droit_aspect', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_droit_follicules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_ovaire_droit_follicules', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_droit_mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_ovaire_droit_mobilite', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_droit_visibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_ovaire_droit_visibilite', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_gauche_accessibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_ovaire_gauche_accessibilite', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_gauche_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_ovaire_gauche_aspect', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_gauche_follicules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_ovaire_gauche_follicules', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_gauche_mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_ovaire_gauche_mobilite', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_gauche_visibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_ovaire_gauche_visibilite', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='position_uterus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_position_uterus', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='structures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_structures', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='titre_echo_pelvienne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_titre_echo_pelvienne', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='type_dispositif_intra_uterin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_type_dispositif_intra_uterin', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='volume_uterin_commentaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_consultationechopelvienne_volume_uterin_commentaire', to='core.ListeChoix'),
        ),
    ]
