# Generated by Django 3.0.8 on 2021-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_auto_20210428_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationcolposcopie',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='consultationecho11sa',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='consultationechocroissance',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='consultationechodeuxiemetrimestre',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='consultationechopelvienne',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='consultationechopremiertrimestre',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='consultationechotroisiemetrimestre',
            name='conclusion',
        ),
        migrations.AddField(
            model_name='consultation',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='conduite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
