# Generated by Django 3.0.8 on 2021-05-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_auto_20210507_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultatanalysebiologique',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='consultationechopelvienne',
            name='conclusion_echo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='conclusion_echo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
