# Generated by Django 3.0.8 on 2021-05-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_patient_ancien_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='duree_gross_j',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='duree_gross_sa',
            field=models.PositiveSmallIntegerField(default=40),
        ),
    ]
