# Generated by Django 3.0.8 on 2021-06-24 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_auto_20210523_2334'),
        ('core', '0136_auto_20210512_1105'),
    ]

    operations = [
    ]
