# Generated by Django 3.0.8 on 2021-05-31 08:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_auto_20210528_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='ajouter_entete_cert_med',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='ajouter_entete_cert_pres',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='ajouter_entete_lettre_acc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='ajouter_entete_ord',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='ajouter_entete_prescr_bio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='modele_presc_analyse_bio',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
