# Generated by Django 3.0.8 on 2021-06-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_antecedentobstetrique_issue_grossesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='t21_1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='t21_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='t21_3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
