# Generated by Django 3.0.8 on 2021-07-06 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_auto_20210705_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencemedecin',
            name='compte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Compte'),
        ),
    ]
