# Generated by Django 3.0.8 on 2021-06-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_analysebiologique_ordre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysebiologique',
            options={'ordering': ['ordre', 'libelle']},
        ),
    ]
