# Generated by Django 3.0.8 on 2021-08-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_auto_20210719_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='patient_rappele',
            field=models.BooleanField(default=False),
        ),
    ]
