# Generated by Django 3.0.8 on 2021-08-14 09:30

from django.db import migrations, models


def update_toxo(apps, schema_editor):
    Grossesse = apps.get_model('core', 'Grossesse')
    for g in Grossesse.objects.all():
        if g.toxoplasmose is None:
            g.toxoplasmose_v2 = ''
        else:
            if g.toxoplasmose:
                g.toxoplasmose_v2 = '1'
            if not g.toxoplasmose:
                g.toxoplasmose_v2 = '0'
        g.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_resultatanalysebiologique_valeur_anormale'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='toxoplasmose_v2',
            field=models.CharField(blank=True, choices=[('', 'Non défini'), ('0', 'Négatif'), ('1', 'Positif')], default='', max_length=256, null=True),
        ),
        migrations.RunPython(update_toxo),
    ]
