# Generated by Django 3.0.8 on 2021-10-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_grossesse_test_t21_fait'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='aspegic',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
