# Generated by Django 3.0.8 on 2021-10-17 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_consultationobstetrique_echo_t3'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='praticien_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Medecin'),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='toxoplasmose_v2',
            field=models.CharField(blank=True, choices=[('', 'Non défini'), ('0', 'Non immunisée'), ('1', 'Immunisée')], default='', max_length=256, null=True),
        ),
    ]
