# Generated by Django 3.0.8 on 2021-10-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_auto_20211018_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='honoraires',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
