# Generated by Django 3.0.8 on 2021-11-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_auto_20211028_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneesfoetus',
            name='opn_presence',
            field=models.CharField(blank=True, choices=[('0', 'Absent'), ('1', 'Présent')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='type',
            field=models.CharField(choices=[('certificat_medical', 'CERTIFICAT MEDICAL'), ('certificat_presence', 'CERTIFICAT MEDICAL DE PRESENCE'), ('lettre_accouchement', "LETTRE D'ACCOUCHEMENT"), ('lettre_confidentielle', 'LETTRE CONFIDENTIELLE'), ('attestation_grossesse', 'ATTESTATION DE GROSSESSE'), ('lettre_fittofly', 'CERTIFICAT MEDICAL FIT TO FLY')], default='certificat_medical', max_length=128),
        ),
    ]
