# Generated by Django 3.0.8 on 2021-11-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_auto_20211106_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='nom_mutuelle',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
