# Generated by Django 3.0.8 on 2021-11-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_reglement_nom_mutuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='default_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Device'),
        ),
        migrations.AddField(
            model_name='worklistitem',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Device'),
        ),
    ]
