# Generated by Django 3.0.8 on 2022-01-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_templateedition_motif_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationobstetrique',
            name='lmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lmc', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationobstetrique',
            name='pelvis_maternel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelvis_maternel', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='donneesfoetus',
            name='morpho_cou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morpho_cou', to='core.ListeChoix'),
        ),
    ]
