# Generated by Django 3.0.8 on 2022-01-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_auto_20220131_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='marge_droite',
            field=models.SmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='marge_gauche',
            field=models.SmallIntegerField(default=20),
        ),
    ]
