# Generated by Django 3.0.8 on 2022-02-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_lignereglement_prix_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='code_conventionnel',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
