# Generated by Django 3.0.8 on 2022-02-20 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_auto_20220218_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bordereau',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='bordereau',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='bordereau',
            name='date_bordereau',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
