# Generated by Django 3.0.8 on 2022-02-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_auto_20220220_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bordereau',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bordereau',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bordereau',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='bordereau',
            name='bordereau_id',
            field=models.IntegerField(),
        ),
    ]
