# Generated by Django 4.0.6 on 2022-12-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_motifconsultation_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='pays',
            field=models.CharField(max_length=128),
        ),
    ]
