# Generated by Django 4.0.6 on 2022-12-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_alter_adresse_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='origine',
            field=models.CharField(blank=True, choices=[('1', 'Europe/Afrique du nord'), ('2', 'Afrique sud-saharienne'), ('3', 'Amérique latine'), ('4', 'Asie'), ('10', 'Autre')], max_length=128, null=True),
        ),
    ]
