# Generated by Django 4.0.6 on 2026-03-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_typeordonnance_default_modeles'),
    ]

    operations = [
        migrations.AddField(
            model_name='listechoix',
            name='libelle_ar',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='listechoix',
            name='libelle_en',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='listechoix',
            name='libelle_es',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
