# Generated by Django 4.0.6 on 2026-04-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0212_listechoix_translations_data2'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasierantecedent',
            name='text_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='phrasierantecedent',
            name='text_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='phrasierantecedent',
            name='text_es',
            field=models.TextField(blank=True, default=''),
        ),
    ]
