# Generated by Django 4.0.6 on 2026-04-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0213_add_phrasier_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='catgeorieantecedent',
            name='libelle_ar',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='catgeorieantecedent',
            name='libelle_en',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='catgeorieantecedent',
            name='libelle_es',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
