# Generated by Django 4.2.29 on 2026-06-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0217_worklistitem_mpps_sop_instance_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageconsultation',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.device'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='statut',
            field=models.CharField(choices=[(1, 'En attente'), (2, 'En consultation'), (3, 'Consultation terminée'), (4, 'Examen terminé'), (10, 'Annulé')], default=1, max_length=2),
        ),
    ]
