# Generated by Django 4.0.6 on 2026-06-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0218_imageconsultation_device_alter_admission_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistitem',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultation', unique=True),
        ),
    ]
