from django.core.management import BaseCommand

from apps.core.models import Compte, TypeOrdonnance, Ordonnance

types = [
    {'libelle': 'Traitements', 'new_libelle': 'Traitements', 'modele': '<div style="text-align: center;"><h4 style="font-size: 14pt;">Ordonnance M&eacute;dicale</h4></div><p><span style="margin-top: 10px;">&nbsp;</span></p><p><strong>&lt;%= civilite %&gt; &lt;%= nom_patient %&gt;</strong></p><br>'},
    {'libelle': 'Examens', 'new_libelle': 'Examens complémentaires', 'modele': '<div style="text-align: center;"><h4 style="font-size: 14pt;">Examen complémentaire</h4></div><p><span style="margin-top: 10px;">&nbsp;</span></p><p><strong>&lt;%= civilite %&gt; &lt;%= nom_patient %&gt;</strong></p><br>'},
    {'libelle': 'Trisomie 21 1er trimestre', 'new_libelle': 'Trisomie 21 1er trimestre', 'modele': '<div style="text-align: center;"><h4 style="font-size: 14pt;">D&eacute;pistage de la trisomie 21 (T1)</h4></div><p><span style="margin-top: 10px;">&nbsp;</span></p><p><span style="font-size: 12pt;"><strong>&lt;%= civilite %&gt; &lt;%= nom_patient %&gt;</strong></span></p><br><p><span style="font-size: 12pt;">Date de naissance: &lt;%= date_naissance %&gt;</span></p><table style="border-collapse: collapse; width: 100%;" border="0" data-pdfmake="{&quot;layout&quot;:&quot;noBorders&quot;}"><tbody><tr><td style="width: 48.4289%;"><span style="font-size: 12pt;">Poids : &lt;%= poids %&gt;</span></td><td style="width: 48.4289%;"><span style="font-size: 12pt;">Tabac : &lt;%= fumeur %&gt;</span></td></tr><tr><td style="width: 48.4289%;"><span style="font-size: 12pt;">Diab&egrave;te : &lt;%= diabete %&gt;</span></td><td style="width: 48.4289%;"><span style="font-size: 12pt;">ATCD de T21 :&nbsp;</span></td></tr><tr><td style="width: 48.4289%;"><span style="font-size: 12pt;">DDR: &lt;%= ddr %&gt;</span></td><td style="width: 48.4289%;"><span style="font-size: 12pt;">FIV : &lt;%= fiv %&gt;</span></td></tr><tr><td style="width: 48.4289%;" colspan="2"><span style="font-size: 12pt;">Echo T1 faite le &lt;%= date_echo_t1 %&gt;<br /></span></td></tr><tr><td style="width: 48.4289%;"><span style="font-size: 12pt;">LCC : &lt;%= lcc %&gt;</span></td><td style="width: 48.4289%;"><span style="font-size: 12pt;">CN : &lt;%= cn %&gt;</span></td></tr><tr><td style="width: 48.4289%;" colspan="2"><span style="font-size: 12pt;">Os propres du nez :&nbsp; &lt;%= opn %&gt;</span></td></tr></tbody></table>'},
    {'libelle': 'Trisomie 21 2ème trimestre', 'new_libelle': 'Trisomie 21 2ème trimestre', 'modele': '<div style="text-align: center;"><h4 style="font-size: 14pt;">D&eacute;pistage de la trisomie 21 (T2)</h4></div><p><span style="margin-top: 10px;">&nbsp;</span></p><p><span style="font-size: 12pt;"><strong>&lt;%= civilite %&gt; &lt;%= nom_patient %&gt;</strong></span></p><br><p><span style="font-size: 12pt;">Date de naissance: &lt;%= date_naissance %&gt;</span></p><table style="border-collapse: collapse; width: 100%;" border="0" data-pdfmake="{&quot;layout&quot;:&quot;noBorders&quot;}"><tbody><tr><td style="width: 48.4289%;"><span style="font-size: 12pt;">Poids : &lt;%= poids %&gt;</span></td><td style="width: 48.4289%;"><span style="font-size: 12pt;">Tabac : &lt;%= fumeur %&gt;</span></td></tr><tr><td style="width: 48.4289%;"><span style="font-size: 12pt;">Diab&egrave;te : &lt;%= diabete %&gt;</span></td><td style="width: 48.4289%;"><span style="font-size: 12pt;">ATCD de T21 :&nbsp;</span></td></tr><tr><td style="width: 48.4289%;"><span style="font-size: 12pt;">DDR: &lt;%= ddr %&gt;</span></td><td style="width: 48.4289%;"><span style="font-size: 12pt;">FIV : &lt;%= fiv %&gt;</span></td></tr><tr><td style="width: 48.4289%;" colspan="2"><span style="font-size: 12pt;">Echo T1 faite le &lt;%= date_echo_t1 %&gt;<br /></span></td></tr><tr><td style="width: 48.4289%;"><span style="font-size: 12pt;">LCC : &lt;%= lcc %&gt;</span></td><td style="width: 48.4289%;"><span style="font-size: 12pt;">CN : &lt;%= cn %&gt;</span></td></tr><tr><td style="width: 48.4289%;" colspan="2"><span style="font-size: 12pt;">Os propres du nez :&nbsp; &lt;%= opn %&gt;</span></td></tr></tbody></table>'},
    {'libelle': 'Echographie morphologique', 'new_libelle': 'Echographie morphologique', 'modele': '<div style="text-align: center;"><h4 style="font-size: 14pt;"><span style="font-size: 14pt;">Demande d\'&eacute;chographie morphologique</span></h4><span style="margin-top: 0px; font-size: 11pt;">A faire de pr&eacute;f&eacute;rence &lt;%= date_prev_echo_morpho %&gt;</span></div><p><br /><span style="font-size: 11pt;"><strong>&lt;%= civilite %&gt; &lt;%= nom_patient %&gt;</strong></span></p><br><p><span style="font-size: 11pt;">&lt;%= atcd %&gt;</span></p><table style="border-collapse: collapse; width: 100%; height: 110px;" border="1" data-pdfmake="{&quot;layout&quot;:&quot;noBorders&quot;}"><tbody><tr style="height: 14px;"><td style="width: 48.4289%; height: 14px;"><span style="font-size: 11pt;">Age: &lt;%= age %&gt;</span></td><td style="width: 48.4289%; height: 14px;"><span style="font-size: 11pt;">Poids : &lt;%= poids %&gt;</span></td></tr><tr style="height: 14px;"><td style="width: 48.4289%; height: 14px;"><span style="font-size: 11pt;">DDR: &lt;%= ddr %&gt;</span></td><td style="width: 48.4289%; height: 14px;"><span style="font-size: 11pt;">FIV : &lt;%= fiv %&gt;</span></td></tr><tr style="height: 14px;"><td style="width: 48.4289%; height: 14px;" colspan="2"><span style="font-size: 11pt;">Echo T1 faite le &lt;%= date_echo_t1 %&gt;<br /></span></td></tr><tr style="height: 14px;"><td style="width: 48.4289%; height: 14px;"><span style="font-size: 11pt;">LCC : &lt;%= lcc %&gt;</span></td><td style="width: 48.4289%; height: 14px;"><span style="font-size: 11pt;">CN : &lt;%= cn %&gt;</span></td></tr><tr style="height: 14px;"><td style="width: 48.4289%; height: 14px;" colspan="2"><span style="font-size: 11pt;">D&eacute;pistage de la Trisomie 21 : &lt;%= risque_t21 %&gt;</span></td></tr></tbody></table>'},
]


class Command(BaseCommand):
    help = "Modifier les modèles des types d'ordonnances de base"

    def handle(self, *args, **options):
        for type in types:
            TypeOrdonnance.objects.filter(libelle=type['libelle']).update(libelle=type['new_libelle'], modele=type['modele'])
        print('Opération terminée')
