# Generated by Django 3.0.8 on 2020-08-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_admission_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='origine',
            field=models.CharField(blank=True, choices=[('1', 'Europe/Afrique du nord'), ('2', 'Afrique sud-saharienne'), ('3', 'Amérique latine'), ('4', 'Asie'), ('10', 'Autre')], default='1', max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='PhrasierAntecedent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CatgeorieAntecedent')),
            ],
        ),
    ]
