# Generated by Django 3.0.8 on 2020-09-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200902_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mot_cle',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
