# Generated by Django 3.0.8 on 2020-09-09 12:57

import apps.core.models
import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200908_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrescompte',
            name='logo',
            field=models.ImageField(blank=True, max_length=128, null=True, storage=apps.core.storage.OverwriteStorage(), upload_to=apps.core.models.logo_storage_path),
        ),
        migrations.AlterField(
            model_name='parametrescompte',
            name='nom_entete',
            field=models.TextField(blank=True, null=True),
        ),
    ]
