# Generated by Django 3.0.8 on 2020-09-16 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patient_mot_cle'),
        ('core', '0007_auto_20200909_1257'),
    ]

    operations = [
    ]
