# Generated by Django 3.0.8 on 2020-09-24 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lieuaccouchement'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lieu_accouchement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.LieuAccouchement'),
        ),
    ]
