# Generated by Django 3.0.8 on 2020-09-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200927_2007'),
        ('core', '0010_auto_20200922_1341'),
    ]

    operations = [
    ]
