# Generated by Django 3.0.8 on 2020-10-08 15:56

import apps.core.models
import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20200927_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='signature',
            field=models.ImageField(blank=True, null=True, storage=apps.core.storage.OverwriteStorage(), upload_to=apps.core.models.repertoire_utilisateur),
        ),
    ]
