# Generated by Django 3.0.8 on 2020-10-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201019_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat',
            name='duree',
            field=models.IntegerField(default=1),
        ),
    ]
