# Generated by Django 3.0.8 on 2020-10-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201015_2148'),
        ('core', '0019_patient_nouveau'),
    ]

    operations = [
    ]
