# Generated by Django 3.0.8 on 2020-11-06 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_reglement_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglement',
            name='Admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Admission'),
        ),
    ]
