# Generated by Django 3.0.8 on 2020-11-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_fature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fature',
            new_name='Facture',
        ),
    ]
