# Generated by Django 3.0.8 on 2020-10-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_prescription_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='adresse',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
