# Generated by Django 3.0.8 on 2020-11-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201030_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='adresse',
        ),
    ]
