# Generated by Django 3.0.8 on 2020-11-01 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_etablissement_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='compte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Compte'),
        ),
    ]
