# Generated by Django 3.0.8 on 2020-11-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201112_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='code',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
