# Generated by Django 3.0.8 on 2020-11-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_etablissement_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
