# Generated by Django 3.0.8 on 2020-11-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_antecedentobstetrique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentobstetrique',
            name='terme',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
