# Generated by Django 3.0.8 on 2020-11-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20201103_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentobstetrique',
            name='allaitement_3',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
