# Generated by Django 3.0.8 on 2020-11-17 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_20201115_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='cloture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cloture'),
        ),
    ]
