# Generated by Django 3.0.8 on 2020-11-17 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_reglement_cloture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglement',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='core.Admission'),
        ),
    ]
