# Generated by Django 3.0.8 on 2020-11-18 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20201118_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationColposcopie',
            fields=[
                ('consultation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Consultation')),
                ('typages', models.CharField(blank=True, max_length=512, null=True)),
                ('commentaires_1', models.TextField(blank=True, null=True)),
                ('commentaires_2', models.TextField(blank=True, null=True)),
                ('commentaires_3', models.TextField(blank=True, null=True)),
                ('biopsie', models.BooleanField(blank=True, null=True)),
                ('commentaires_4', models.TextField(blank=True, null=True)),
                ('conculsion', models.TextField(blank=True, null=True)),
                ('acide_acetique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acide_acetique', to='core.ListeChoix')),
                ('examen_sans_preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examen_sans_preparation', to='core.ListeChoix')),
                ('indications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indications_colposcopie', to='core.ListeChoix')),
                ('localisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localisation', to='core.ListeChoix')),
                ('lugol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lugol', to='core.ListeChoix')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag', to='core.ListeChoix')),
                ('test_hpv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_hpv', to='core.ListeChoix')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.consultation',),
        ),
    ]
