# Generated by Django 3.0.8 on 2020-11-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_consultationcolposcopie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationcolposcopie',
            old_name='typages',
            new_name='typage',
        ),
    ]
