# Generated by Django 3.0.8 on 2020-11-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20201119_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationEchoPelvienne',
            fields=[
                ('consultation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Consultation')),
                ('longueur', models.FloatField(blank=True, null=True)),
                ('largeur', models.FloatField(blank=True, null=True)),
                ('hauteur', models.FloatField(blank=True, null=True)),
                ('longueur_totale', models.FloatField(blank=True, null=True)),
                ('volume_uterin', models.FloatField(blank=True, null=True)),
                ('paroi_anterieure', models.FloatField(blank=True, null=True)),
                ('paroi_posterieure', models.FloatField(blank=True, null=True)),
                ('commentaires_myometre', models.TextField(blank=True, null=True)),
                ('largeur_interostiale', models.FloatField(blank=True, null=True)),
                ('hysterometrie', models.FloatField(blank=True, null=True)),
                ('dispositif_intra_tubaire', models.BooleanField(blank=True, null=True)),
                ('col_longueur', models.FloatField(blank=True, null=True)),
                ('commentaire_col_endometre', models.TextField(blank=True, null=True)),
                ('ovaire_gauche_longueur', models.FloatField(blank=True, null=True)),
                ('ovaire_gauche_largeur', models.FloatField(blank=True, null=True)),
                ('ovaire_gauche_hauteur', models.FloatField(blank=True, null=True)),
                ('ovaire_gauche_volume', models.FloatField(blank=True, null=True)),
                ('ovaire_droit_longueur', models.FloatField(blank=True, null=True)),
                ('ovaire_droit_largeur', models.FloatField(blank=True, null=True)),
                ('ovaire_droit_hauteur', models.FloatField(blank=True, null=True)),
                ('ovaire_droit_volume', models.FloatField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('anomalies_dispositif_intra_uterin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies_dispositif_intra_uterin', to='core.ListeChoix')),
                ('asymetrie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asymetrie', to='core.ListeChoix')),
                ('cavite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cavite', to='core.ListeChoix')),
                ('col_aspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='col_aspect', to='core.ListeChoix')),
                ('col_vascularisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='col_vascularisation', to='core.ListeChoix')),
                ('cul_de_sac_latero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cul_de_sac_latero', to='core.ListeChoix')),
                ('endometre_echogenicite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endometre_echogenicite', to='core.ListeChoix')),
                ('endometre_visualisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endometre_visualisation', to='core.ListeChoix')),
                ('lateralisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lateralisation', to='core.ListeChoix')),
                ('ligne_cavitaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne_cavitaire', to='core.ListeChoix')),
                ('localisation_dispositif_intra_uterin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localisation_dispositif_intra_uterin', to='core.ListeChoix')),
                ('malformation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malformation', to='core.ListeChoix')),
                ('mobilite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilite', to='core.ListeChoix')),
                ('ovaire_droit_accessibilite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovaire_droit_accessibilite', to='core.ListeChoix')),
                ('ovaire_droit_aspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovaire_droit_aspect', to='core.ListeChoix')),
                ('ovaire_droit_commentaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovaire_droit_commentaire', to='core.ListeChoix')),
                ('ovaire_droit_follicules', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovaire_droit_follicules', to='core.ListeChoix')),
                ('ovaire_droit_visibilite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovaire_droit_visibilite', to='core.ListeChoix')),
                ('ovaire_gauche_accessibilite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovaire_gauche_accessibilite', to='core.ListeChoix')),
                ('ovaire_gauche_aspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovaire_gauche_aspect', to='core.ListeChoix')),
                ('ovaire_gauche_commentaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovaire_gauche_commentaire', to='core.ListeChoix')),
                ('ovaire_gauche_follicules', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovaire_gauche_follicules', to='core.ListeChoix')),
                ('ovaire_gauche_visibilite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovaire_gauche_visibilite', to='core.ListeChoix')),
                ('position_uterus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_uterus', to='core.ListeChoix')),
                ('structures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='core.ListeChoix')),
                ('titre_echo_pelvienne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titre_echo_pelvienne', to='core.ListeChoix')),
                ('type_dispositif_intra_uterin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_dispositif_intra_uterin', to='core.ListeChoix')),
                ('volume_uterin_commentaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volume_uterin_commentaire', to='core.ListeChoix')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.consultation',),
        ),
        migrations.CreateModel(
            name='Myome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConsultationEchoPelvienne')),
            ],
        ),
    ]
