# Generated by Django 3.0.8 on 2020-11-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_consultationechopelvienne_myome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_droit_commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_gauche_commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
