# Generated by Django 3.0.8 on 2020-11-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20201123_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationechopelvienne',
            name='ovaire_droit_mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovaire_droit_mobilite', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationechopelvienne',
            name='ovaire_gauche_mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ovaire_gauche_mobilite', to='core.ListeChoix'),
        ),
    ]
