# Generated by Django 3.0.8 on 2020-11-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20201124_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='myome',
            name='calcifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calcifications', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='myome',
            name='contours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countours', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='myome',
            name='diametre_moyen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myome',
            name='hauteur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myome',
            name='largeur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myome',
            name='longueur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myome',
            name='mure_posterieur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myome',
            name='situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situation', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='myome',
            name='situation_coupe_longitudinale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situation_coupe_longitudinale', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='myome',
            name='situation_coupe_transversale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situation_coupe_transversale', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='myome',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='myome',
            name='type_figo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_figo', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='myome',
            name='vascularisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vascularisation', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='myome',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
