# Generated by Django 3.0.8 on 2020-11-28 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_grossesse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grossesse',
            old_name='donnee_grossesse',
            new_name='nb_foetus',
        ),
    ]
