# Generated by Django 3.0.8 on 2020-11-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20201128_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='type_grossesse',
            field=models.CharField(choices=[('bichoriale_biamniotique', 'bichoriale biamniotique'), ('monochoriale_biamniotique', 'monochoriale biamniotique'), ('monochoriale_monoamniotique', 'monochoriale monoamniotique')], default='', max_length=256),
        ),
    ]
