# Generated by Django 3.0.8 on 2020-11-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20201128_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='caryotype_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caryotype', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='caryotype_val',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='diabete',
            field=models.CharField(choices=[('diabete_gest_regime', 'Diabète gestationnel sous régime seul'), ('diabete_gest_insul', 'Diabète gestationnel sous insuline'), ('hgpo', 'HGPO Normale'), ('diabete_1', 'Diabète type 1'), ('diabete_2', 'Diabète type 2')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='dpni',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='msres_1_type',
            field=models.CharField(choices=[('technique', 'Technique'), ('papp-a', 'PAPP-A'), ('afp', 'AFP')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='msres_1_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='msres_2_type',
            field=models.CharField(choices=[('technique', 'Technique'), ('papp-a', 'PAPP-A'), ('afp', 'AFP')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='msres_2_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='risque',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
