# Generated by Django 3.0.8 on 2020-11-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20201128_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='cn_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='lcc_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='score_herman_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='conception',
            field=models.CharField(choices=[('', ''), ('spontannee', 'Spontannée'), ('iac', 'IAC'), ('fiv', 'FIV')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='consanguinite_conjoint',
            field=models.CharField(choices=[('', ''), ('cousin', 'Cousin')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='diabete',
            field=models.CharField(choices=[('', ''), ('diabete_gest_regime', 'Diabète gestationnel sous régime seul'), ('diabete_gest_insul', 'Diabète gestationnel sous insuline'), ('hgpo', 'HGPO Normale'), ('diabete_1', 'Diabète type 1'), ('diabete_2', 'Diabète type 2')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='msres_1_type',
            field=models.CharField(choices=[('', ''), ('technique', 'Technique'), ('papp-a', 'PAPP-A'), ('afp', 'AFP')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='msres_2_type',
            field=models.CharField(choices=[('', ''), ('technique', 'Technique'), ('freebeta', 'FreeBeta'), ('bhcg', 'BhCG')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='nb_foetus',
            field=models.CharField(choices=[('', ''), ('unique', 'Unique'), ('gemellaire', 'Gémellaire'), ('triple', 'Triple')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='type_grossesse',
            field=models.CharField(choices=[('', ''), ('bichoriale_biamniotique', 'bichoriale biamniotique'), ('monochoriale_biamniotique', 'monochoriale biamniotique'), ('monochoriale_monoamniotique', 'monochoriale monoamniotique')], default='', max_length=256),
        ),
    ]
