# Generated by Django 3.0.8 on 2020-12-22 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20201129_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationObstetrique',
            fields=[
                ('consultation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Consultation')),
                ('rdv_suivant_apres', models.DateField(blank=True, null=True)),
                ('rdv_suivant_avant', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.consultation',),
        ),
        migrations.CreateModel(
            name='ConsultationEcho11SA',
            fields=[
                ('consultationobstetrique_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ConsultationObstetrique')),
                ('sac_gestationnel_longueur', models.FloatField(blank=True, null=True)),
                ('sac_gestationnel_largeur', models.FloatField(blank=True, null=True)),
                ('sac_gestationnel_hauteur', models.FloatField(blank=True, null=True)),
                ('sac_gestationnel_diametre', models.FloatField(blank=True, null=True)),
                ('embryon_visible', models.BooleanField(default=True)),
                ('lcc', models.FloatField(blank=True, null=True)),
                ('bip', models.FloatField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('activite_cardiaque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activite_cardiaque', to='core.ListeChoix')),
                ('morpho_extremite_cephalique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morpho_extremite_cephalique', to='core.ListeChoix')),
                ('morpho_membres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morpho_membres', to='core.ListeChoix')),
                ('sac_gestationnel_decollement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sac_gestationnel_decollement', to='core.ListeChoix')),
                ('sac_gestationnel_localisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sac_gestationnel_localisation', to='core.ListeChoix')),
                ('sac_gestationnel_tonicite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sac_gestationnel_tonicite', to='core.ListeChoix')),
                ('sac_gestationnel_trophoblaste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sac_gestationnel_trophoblaste', to='core.ListeChoix')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.consultationobstetrique',),
        ),
    ]
