# Generated by Django 3.0.8 on 2020-12-25 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20201225_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationobstetrique',
            name='col_entonnoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='col_entonnoir', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='consultationobstetrique',
            name='col_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationobstetrique',
            name='col_orifice_interne',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
