# Generated by Django 3.0.8 on 2020-12-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20201226_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneesfoetus',
            name='morpho_pole_cepha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morpho_pole_cepha', to='core.ListeChoix'),
        ),
    ]
