# Generated by Django 3.0.8 on 2020-12-26 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20201226_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignereglement',
            name='reglement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_reglement', to='core.Reglement'),
        ),
    ]
