# Generated by Django 3.0.8 on 2020-12-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20201226_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='reglement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.Reglement'),
        ),
    ]
