# Generated by Django 3.0.8 on 2020-12-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20201227_1428'),
        ('core', '0055_merge_20201224_2129'),
    ]

    operations = [
    ]
