# Generated by Django 3.0.8 on 2020-12-29 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_merge_20201229_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationobstetrique',
            name='grossesse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Grossesse'),
            preserve_default=False,
        ),
    ]
