# Generated by Django 3.0.8 on 2020-12-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_consultationobstetrique_grossesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='grossesse_patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Grossesse'),
            preserve_default=False,
        ),
    ]
