# Generated by Django 3.0.8 on 2021-01-20 20:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_consultationechopelvienne_adenomyose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='adenomyose',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
