# Generated by Django 3.0.8 on 2021-01-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_imageconsultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageconsultation',
            name='type',
            field=models.CharField(choices=[('G', 'Graphique'), ('E', 'Echographie')], default='G', max_length=1),
            preserve_default=False,
        ),
    ]
