# Generated by Django 3.0.8 on 2021-01-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20210128_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysebiologique',
            name='unite',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
