# Generated by Django 3.0.8 on 2021-01-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20210129_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysebiologique',
            options={'ordering': ['libelle']},
        ),
        migrations.AlterModelOptions(
            name='collectionanalysebiologique',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='prescriptionanalysebiologique',
            options={'ordering': ['-date_prescription']},
        ),
        migrations.AlterField(
            model_name='resultatanalysebiologique',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultatanalysebiologique',
            name='valeur',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
