# Generated by Django 3.0.8 on 2021-02-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20210129_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='ajouter_antecedents_edition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='ajouter_signature_edition',
            field=models.BooleanField(default=True),
        ),
    ]
