# Generated by Django 3.0.8 on 2021-02-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20210202_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date']},
        ),
    ]
