# Generated by Django 3.0.8 on 2021-02-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20210207_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='evacuation_grossesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evacuation_grossesse', to='core.ListeChoix'),
        ),
    ]
