# Generated by Django 3.0.8 on 2021-02-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_parametrescompte_ajouter_entetes_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='compte',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='core.Compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestation',
            name='par_defaut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='forme',
            field=models.CharField(choices=[('comprime', 'Comprimé'), ('gelule', 'Gélule'), ('gel', 'Gel'), ('gouttes', 'Gouttes'), ('injection', 'Injection'), ('pommade', 'Pommade'), ('poudre', 'Poudre'), ('sirop', 'Sirop'), ('suppositoire', 'Suppositoire'), ('autre', 'Autre')], default='comprime', max_length=256),
        ),
    ]
