# Generated by Django 3.0.8 on 2021-02-23 14:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20210217_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('requested_procedure_description', models.CharField(blank=True, max_length=256, null=True)),
                ('requested_procedure_id', models.CharField(blank=True, max_length=256, null=True)),
                ('mpps_status', models.CharField(choices=[(0, 'pending'), (1, 'created'), (2, 'completed')], default=1, max_length=2)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConsultationObstetrique')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=256)),
                ('modele', models.CharField(max_length=256)),
                ('mise_circulation', models.DateField(blank=True, null=True)),
                ('informations', models.CharField(max_length=512)),
                ('reference', models.CharField(max_length=256)),
                ('ae_title', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=11)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Compte')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
