# Generated by Django 3.0.8 on 2021-02-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_auto_20210223_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='informations',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='reference',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='worklistitem',
            name='mpps_status',
            field=models.CharField(choices=[(0, 'pending'), (1, 'created'), (2, 'completed')], default=0, max_length=2),
        ),
    ]
