# Generated by Django 3.0.8 on 2021-03-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_auto_20210301_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistitem',
            name='mpps_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('IN PROGRESS', 'inprogress'), ('COMPLETED', 'completed'), ('DISCONTINUED', 'discontinued')], default='PENDING', max_length=128),
        ),
    ]
