# Generated by Django 3.0.8 on 2021-03-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_templateedition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateedition',
            name='categorie_consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_consultation', to='core.CategorieConsultation'),
        ),
    ]
