# Generated by Django 3.0.8 on 2021-03-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_auto_20210309_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationechopelvienne',
            name='adenomyose_conclusion',
            field=models.ManyToManyField(blank=True, related_name='adenomyose_conclusion', to='core.ListeChoix'),
        ),
    ]
