# Generated by Django 3.0.8 on 2021-03-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_auto_20210324_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeChoixActif',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.profil',),
        ),
    ]
