# Generated by Django 3.0.8 on 2021-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_listechoixactif'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='screening_deuxieme_trimestre',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='screening_premier_trimestre',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='antecedentobstetrique',
            name='lieu_accouchement_principal',
            field=models.CharField(blank=True, choices=[('H', 'Hôpital'), ('C', 'Clinique'), ('A', 'Autre')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='lieu_accouchement_principal',
            field=models.CharField(blank=True, choices=[('H', 'Hôpital'), ('C', 'Clinique'), ('A', 'Autre')], max_length=1),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='categorie',
            field=models.CharField(choices=[('examen_complementaire', 'Examen complémentaire')], default='', max_length=256),
        ),
    ]
