# Generated by Django 3.0.8 on 2021-04-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_auto_20210402_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date', '-id']},
        ),
    ]
