# Generated by Django 3.0.8 on 2021-04-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_auto_20210406_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentobstetrique',
            name='grossesse',
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='grossesse',
            field=models.ManyToManyField(blank=True, related_name='grossesse', to='core.ListeChoix'),
        ),
    ]
