# Generated by Django 3.0.8 on 2021-04-12 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_auto_20210412_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='conception_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conception', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='diabete_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diabete', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='msres_1_type_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msres_1_type', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='msres_2_type_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msres_2_type', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='score_herman_1_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_herman_1', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='score_herman_2_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_herman_2', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='score_herman_3_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_herman_3', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='type_grossesse_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_grossesse', to='core.ListeChoix'),
        ),
    ]
