# Generated by Django 3.0.8 on 2021-04-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_auto_20210421_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitementvaleurpma',
            name='traitement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TraitementPMA'),
        ),
    ]
