# Generated by Django 3.0.8 on 2021-04-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_auto_20210421_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitementvaleurpma',
            name='rang',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
