# Generated by Django 3.0.8 on 2021-05-06 08:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_resultatanalysebiologique_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat',
            name='type',
            field=models.CharField(choices=[('certificat_medical', 'Certificat médical'), ('certificat_presence', 'Certificat de présence'), ('lettre_accouchement', "Lettre d'accouchement")], default='certificat_medical', max_length=128),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='modele_certificat_medical',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='modele_certificat_presence',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='modele_lettre_accouchement',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TypeOrdonnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('libelle', models.CharField(max_length=256)),
                ('modele', models.TextField(blank=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Compte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.TypeOrdonnance'),
        ),
    ]
