# Generated by Django 3.0.8 on 2021-05-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_absencemedecin_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencemedecin',
            name='date_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='absencemedecin',
            name='date_fin',
            field=models.DateTimeField(),
        ),
    ]
