# Generated by Django 3.0.8 on 2021-05-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_auto_20210506_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificat',
            name='type',
            field=models.CharField(choices=[('certificat_medical', 'Certificat médical'), ('certificat_presence', 'Certificat médical de présence'), ('lettre_accouchement', "Lettre d'accouchement")], default='certificat_medical', max_length=128),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='code',
            field=models.CharField(max_length=128),
        ),
    ]
