# Generated by Django 3.0.8 on 2021-06-24 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_merge_20210624_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotifAbsence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('motif', models.CharField(max_length=128)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Compte')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
