# Generated by Django 3.0.8 on 2021-06-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_auto_20210531_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='msres_1_mom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='msres_2_mom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='risque_t18_13',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='risque_t21_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='risque_t21_bio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='msres_1_type',
            field=models.CharField(blank=True, choices=[('', ''), ('papp-a', 'PAPP-A'), ('afp', 'AFP')], default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='msres_2_type',
            field=models.CharField(blank=True, choices=[('', ''), ('freebeta', 'FreeBeta'), ('bhcg', 'BhCG')], default='', max_length=256, null=True),
        ),
    ]
