# Generated by Django 3.0.8 on 2021-07-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_absencemedecin_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencemedecin',
            name='praticien_remplacant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Praticien'),
        ),
    ]
