# Generated by Django 3.0.8 on 2021-06-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_auto_20210601_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationobstetrique',
            name='echo_morpho',
            field=models.TextField(blank=True, null=True),
        ),
    ]
