# Generated by Django 3.0.8 on 2021-06-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_consultationobstetrique_echo_morpho'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_12_sa',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_22_sa',
            field=models.PositiveSmallIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_32_sa',
            field=models.PositiveSmallIntegerField(default=32),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_datation_sa_1',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_datation_sa_2',
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_t1_sa_1',
            field=models.PositiveSmallIntegerField(default=11),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_t1_sa_2',
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_t2_sa_1',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_t2_sa_2',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_t3_sa_1',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_t3_sa_2',
            field=models.PositiveSmallIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_gly_sa_1',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_gly_sa_2',
            field=models.PositiveSmallIntegerField(default=28),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_triso_1_sa_1',
            field=models.PositiveSmallIntegerField(default=11),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_triso_1_sa_2',
            field=models.PositiveSmallIntegerField(default=13),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_triso_2_sa_1',
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_triso_2_sa_2',
            field=models.PositiveSmallIntegerField(default=18),
        ),
    ]
