# Generated by Django 3.0.8 on 2021-07-19 11:33

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_auto_20210627_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='footer_a4',
            field=models.ImageField(blank=True, max_length=128, null=True, upload_to=apps.core.models.footer_storage_path_a4),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='logo_a4',
            field=models.ImageField(blank=True, max_length=128, null=True, upload_to=apps.core.models.logo_storage_path_a4),
        ),
        migrations.AlterField(
            model_name='praticien',
            name='titre',
            field=models.CharField(choices=[('Dr', 'Dr'), ('Pr', 'Pr'), ('Mme', 'Mme'), ('Mlle', 'Mlle'), ('Mr', 'Mr')], default='Dr', max_length=8),
        ),
    ]
