# Generated by Django 3.0.8 on 2021-08-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_alertepatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatanalysebiologique',
            name='valeur_anormale',
            field=models.BooleanField(default=False),
        ),
    ]
