# Generated by Django 3.0.8 on 2021-08-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_grossesse_toxoplasmose_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationgynecologique',
            name='date_mariage',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interrogatoirepma',
            name='date_mariage',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_mariage',
            field=models.DateField(blank=True, null=True),
        ),
    ]
