# Generated by Django 3.0.8 on 2021-08-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_auto_20210814_2133'),
        ('core', '0143_auto_20210713_2010'),
    ]

    operations = [
    ]
