# Generated by Django 3.0.8 on 2021-08-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_merge_20210823_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeoperatoire',
            name='observation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='programmeoperatoire',
            name='type_acte',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
