# Generated by Django 3.0.8 on 2021-09-28 20:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_auto_20210907_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='modele_lettre_confidentielle',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='msres_1_type',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='msres_2_type',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
