# Generated by Django 3.0.8 on 2021-10-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_auto_20211017_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='nom_naissance',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
