# Generated by Django 3.0.8 on 2021-10-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_rdv_nom_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='praticien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Medecin'),
        ),
    ]
