# Generated by Django 3.0.8 on 2021-10-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_admission_praticien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='nom',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
