# Generated by Django 3.0.8 on 2021-10-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_auto_20211024_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='ajouter_entete_attestation_grossesse',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='ajouter_entete_lettre_confidentielle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='ajouter_entete_lettre_fittofly',
            field=models.BooleanField(default=True),
        ),
    ]
