# Generated by Django 3.0.8 on 2021-11-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_auto_20211114_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrogatoirepma',
            name='conduite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
