# Generated by Django 3.0.8 on 2021-11-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_interrogatoirepma_conduite'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrogatoirepma',
            name='duree_infertilite_mois',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interrogatoirepma',
            name='nb_paillettes',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interrogatoirepma',
            name='rendement',
            field=models.CharField(blank=True, choices=[('bon', 'Bon'), ('mauvais', 'Mauvais')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='interrogatoirepma',
            name='sperme_congenalation_clinique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Etablissement'),
        ),
    ]
