# Generated by Django 3.0.8 on 2021-12-12 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_auto_20211123_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='motif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.MotifRdv'),
        ),
    ]
