# Generated by Django 3.0.8 on 2021-12-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_parametrescompte_ajouter_date_courriers'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='marge_entete',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='marge_footer',
            field=models.SmallIntegerField(default=80),
        ),
    ]
