# Generated by Django 3.0.8 on 2022-01-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_auto_20211218_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneesfoetus',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
