# Generated by Django 3.0.8 on 2022-01-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_auto_20211218_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='caisse_affectation',
            field=models.CharField(blank=True, choices=[('1', 'CNRPS'), ('2', 'CNSS')], default='1', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='code_apci',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='code_medecin_famille',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_validite_mutuelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='designation',
            field=models.TextField(blank=True, default='CNAM'),
        ),
        migrations.AddField(
            model_name='patient',
            name='lien_parente',
            field=models.CharField(blank=True, choices=[('1', 'Assuré'), ('2', 'Conjoint'), ('3', 'Enfant'), ('4', 'Pere'), ('5', 'Mere')], default='1', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mutuelle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='num_carnet_soin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='regime',
            field=models.CharField(blank=True, choices=[('1', 'Tiers payant'), ('2', 'Remboursement'), ('3', 'Publique')], default='1', max_length=128, null=True),
        ),
    ]
