# Generated by Django 3.0.8 on 2022-01-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_auto_20220117_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='designation',
            field=models.CharField(default='CNAM', max_length=128),
        ),
    ]
