# Generated by Django 3.0.8 on 2022-02-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_prestation_prix_pec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglement',
            name='mutuelle',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
