# Generated by Django 3.0.8 on 2022-02-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_auto_20220204_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglement',
            name='mutuelle',
            field=models.BooleanField(default=True),
        ),
    ]
