# Generated by Django 3.0.8 on 2022-02-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_auto_20220131_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneesfoetus',
            name='morpho_liquide_amnio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morpho_liquide_amnio', to='core.ListeChoix'),
        ),
    ]
