# Generated by Django 3.0.8 on 2022-02-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_auto_20220210_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignereglement',
            name='prix_initial',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
