# Generated by Django 3.0.8 on 2022-02-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_profil_code_conventionnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bordereau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bordereau_id', models.CharField(max_length=128)),
                ('nom_medecin', models.CharField(blank=True, max_length=128, null=True)),
                ('code_conventionnel', models.CharField(blank=True, max_length=128, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
    ]
