# Generated by Django 3.0.8 on 2022-02-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_auto_20220222_0026'),
        ('core', '0192_parametrescompte_ajouter_date_cro'),
    ]

    operations = [
    ]
