# Generated by Django 4.0.6 on 2022-10-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_merge_20220227_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='adenomyose',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_adenomyose', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='adenomyose_conclusion',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_adenomyose_conclusion', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='anomalies_dispositif_intra_uterin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_anomalies_dispositif_intra_uterin', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='asymetrie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_asymetrie', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='cavite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cavite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='col_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_col_aspect', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='col_vascularisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_col_vascularisation', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='cul_de_sac_latero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cul_de_sac_latero', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='endometre_echogenicite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_endometre_echogenicite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='endometre_visualisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_endometre_visualisation', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='lateralisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_lateralisation', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ligne_cavitaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ligne_cavitaire', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='localisation_dispositif_intra_uterin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_localisation_dispositif_intra_uterin', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='malformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_malformation', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_mobilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_droit_accessibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_droit_accessibilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_droit_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_droit_aspect', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_droit_follicules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_droit_follicules', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_droit_mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_droit_mobilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_droit_visibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_droit_visibilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_gauche_accessibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_gauche_accessibilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_gauche_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_gauche_aspect', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_gauche_follicules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_gauche_follicules', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_gauche_mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_gauche_mobilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='ovaire_gauche_visibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_gauche_visibilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='position_uterus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_position_uterus', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='structures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_structures', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='titre_echo_pelvienne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_titre_echo_pelvienne', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='type_dispositif_intra_uterin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_type_dispositif_intra_uterin', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationechopelvienne',
            name='volume_uterin_commentaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_volume_uterin_commentaire', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='adenomyose',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_adenomyose', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='adenomyose_conclusion',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_adenomyose_conclusion', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='anomalies_dispositif_intra_uterin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_anomalies_dispositif_intra_uterin', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='asymetrie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_asymetrie', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='cavite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cavite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='col_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_col_aspect', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='col_vascularisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_col_vascularisation', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='cul_de_sac_latero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cul_de_sac_latero', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='endometre_echogenicite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_endometre_echogenicite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='endometre_visualisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_endometre_visualisation', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='lateralisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_lateralisation', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='ligne_cavitaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ligne_cavitaire', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='localisation_dispositif_intra_uterin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_localisation_dispositif_intra_uterin', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='malformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_malformation', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_mobilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='ovaire_droit_accessibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_droit_accessibilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='ovaire_droit_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_droit_aspect', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='ovaire_droit_follicules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_droit_follicules', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='ovaire_droit_mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_droit_mobilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='ovaire_droit_visibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_droit_visibilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_accessibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_gauche_accessibilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_gauche_aspect', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_follicules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_gauche_follicules', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_mobilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_gauche_mobilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='ovaire_gauche_visibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ovaire_gauche_visibilite', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='position_uterus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_position_uterus', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='structures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_structures', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='titre_echo_pelvienne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_titre_echo_pelvienne', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='type_dispositif_intra_uterin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_type_dispositif_intra_uterin', to='core.listechoix'),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='volume_uterin_commentaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_volume_uterin_commentaire', to='core.listechoix'),
        ),
    ]
