# Generated by Django 4.2.29 on 2026-04-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0215_waveformconsultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caisse_affectation',
            field=models.CharField(blank=True, choices=[('CNSS', 'CNSS'), ('CNRPS', 'CNRPS')], default='CNSS', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='designation',
            field=models.CharField(choices=[('CNAM', "CNAM - Caisse Nationale d'Assurance Maladie"), ('CNSS', 'CNSS - Caisse Nationale de Sécurité Sociale'), ('CNRPS', 'CNRPS - Caisse Nationale de Retraite et de Prévoyance Sociale'), ('CNAV', "CNAV - Caisse Nationale d'Assurance Vieillesse"), ('MILAT', 'MILAT - Militaires'), ('SGO', 'SGO - Groupe Specialisé')], default='CNAM', max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='regime',
            field=models.CharField(blank=True, choices=[('1', 'Tiers payant'), ('2', 'Remboursement'), ('3', 'Publique'), ('4', 'Gratuit')], default='1', max_length=128, null=True),
        ),
    ]
