# Generated by Django 4.0.6 on 2026-06-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0216_mutuelle_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklistitem',
            name='mpps_sop_instance_uid',
            field=models.CharField(blank=True, db_index=True, help_text='MPPS SOP Instance UID for N-SET matching', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='pays',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
