# Generated by Django 4.2.29 on 2026-07-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0219_alter_worklistitem_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='core.medecin'),
        ),
    ]
