# Generated by Django 3.0.8 on 2020-07-18 02:52

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rue', models.CharField(blank=True, max_length=128, null=True)),
                ('cite', models.CharField(blank=True, max_length=128, null=True)),
                ('ville', models.CharField(blank=True, max_length=128, null=True)),
                ('cp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gouvernorat', models.CharField(blank=True, max_length=128, null=True)),
                ('pays', models.CharField(default='Tunisie', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CatgeorieAntecedent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=128)),
                ('telephone', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('langue', models.CharField(default='fr', max_length=8)),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Adresse')),
                ('categories_consultations', models.ManyToManyField(blank=True, to='core.CategorieConsultation')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DossierFichiersPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MotifRdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SousCatgeorieAntecedent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=128)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CatgeorieAntecedent')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(choices=[('dr', 'Docteur'), ('pr', 'Professeur'), ('mme', 'Madame'), ('mlle', 'Mademoiselle'), ('mr', 'Monsieur')], max_length=8)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone_principal', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to=apps.core.models.Compte.storage_path)),
                ('code_securite_sociale', models.CharField(blank=True, max_length=128, null=True)),
                ('enligne', models.SmallIntegerField(default=0)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Compte')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Praticien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=128)),
                ('nom', models.CharField(max_length=128)),
                ('specialite', models.CharField(max_length=128)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Compte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('mme', 'Madame'), ('mlle', 'Mademoiselle'), ('mr', 'Monsieur')], default='mme', max_length=8)),
                ('prenom', models.CharField(max_length=128)),
                ('nom', models.CharField(max_length=128)),
                ('nom_naissance', models.CharField(blank=True, max_length=128, null=True)),
                ('sexe', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], default='F', max_length=1)),
                ('date_naissance', models.DateField()),
                ('numero_identite', models.CharField(blank=True, max_length=128, null=True)),
                ('code_securite_sociale', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, null=True)),
                ('profession', models.CharField(blank=True, max_length=128, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A-', 'A négatif'), ('A+', 'A positif'), ('B-', 'B négatif'), ('B+', 'B positif'), ('AB-', 'AB négatif'), ('AB+', 'AB positif'), ('O-', 'O négatif'), ('O+', 'O positif')], max_length=3, null=True)),
                ('fumeur', models.BooleanField(default=False)),
                ('nombre_cigarettes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('origine', models.CharField(blank=True, choices=[(1, 'Europe/Afrique du nord'), (2, 'Afrique sud-saharienne'), (3, 'Amérique latine'), (4, 'Asie'), (10, 'Autre')], max_length=128, null=True)),
                ('antecedents_familiaux', models.TextField(blank=True, null=True)),
                ('antecedents_medico_chirurgicaux', models.TextField(blank=True, null=True)),
                ('antecedents_gynecologiques', models.TextField(blank=True, null=True)),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Adresse')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Compte')),
                ('praticiens_correspondants', models.ManyToManyField(to='core.Praticien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotifConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CategorieConsultation')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaireConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Consultation')),
            ],
        ),
        migrations.CreateModel(
            name='FichierPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('fichier', models.FileField(upload_to=apps.core.models.repertoire_patient)),
                ('date', models.DateTimeField()),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DossierFichiersPatient')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='motif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MotifConsultation'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient'),
        ),
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
                ('sous_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SousCatgeorieAntecedent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.profil',),
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('ancien_debut', models.DateTimeField(blank=True, null=True)),
                ('prenom', models.CharField(max_length=128)),
                ('nom', models.CharField(max_length=128)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('cp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=128, null=True)),
                ('gouvernorat', models.CharField(blank=True, max_length=128, null=True)),
                ('nouveau', models.BooleanField(default=True)),
                ('observation', models.CharField(blank=True, max_length=256, null=True)),
                ('statut', models.CharField(choices=[(1, 'Confirmé'), (2, 'En salle'), (3, 'Consultation terminée'), (10, 'Annulé')], default=1, max_length=2)),
                ('motif_modification', models.CharField(blank=True, max_length=128, null=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Compte')),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MotifRdv')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Patient')),
                ('praticien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Medecin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParametresCompte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(blank=True, max_length=128, null=True)),
                ('duree_rdv_defaut', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Compte')),
                ('praticien_defaut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Medecin')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='praticien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Medecin'),
        ),
    ]
