# Generated by Django 3.0.8 on 2020-11-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20201103_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedentobstetrique',
            old_name='allaitement',
            new_name='allaitement_3',
        ),
        migrations.RenameField(
            model_name='antecedentobstetrique',
            old_name='prenom',
            new_name='prenom_1',
        ),
        migrations.RenameField(
            model_name='antecedentobstetrique',
            old_name='terme',
            new_name='prenom_2',
        ),
        migrations.RenameField(
            model_name='antecedentobstetrique',
            old_name='sexe',
            new_name='sexe_1',
        ),
        migrations.RemoveField(
            model_name='antecedentobstetrique',
            name='etat_sante',
        ),
        migrations.RemoveField(
            model_name='antecedentobstetrique',
            name='poids_naissance',
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='allaitement_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='allaitement_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='etat_sante_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etat_sante_1', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='etat_sante_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etat_sante_2', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='etat_sante_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etat_sante_3', to='core.ListeChoix'),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='poids_naissance_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='poids_naissance_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='poids_naissance_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='prenom_3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='sexe_2',
            field=models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin'), ('I', 'Inconnu')], max_length=1),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='sexe_3',
            field=models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin'), ('I', 'Inconnu')], max_length=1),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='terme_1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='terme_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='terme_3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='antecedentobstetrique',
            name='date_accouchement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
