# Generated by Django 3.0.8 on 2020-11-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20201103_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentobstetrique',
            name='nb_foetus',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
    ]
