# Generated by Django 3.0.8 on 2020-12-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_donneesfoetus_morpho_pole_cepha'),
        ('core', '0039_reglement_date_creation'),
    ]

    operations = [
    ]
