# Generated by Django 3.0.8 on 2021-03-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_auto_20210326_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordonnance',
            options={'ordering': ['-date']},
        ),
    ]
