# Generated by Django 3.0.8 on 2021-06-30 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_motifabsence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencemedecin',
            name='motif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.MotifAbsence'),
        ),
    ]
