# Generated by Django 3.0.8 on 2021-06-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_auto_20210626_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_12_j',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_22_j',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_32_j',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_datation_j_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_datation_j_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_t1_j_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_t1_j_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_t2_j_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_t2_j_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_t3_j_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_echo_t3_j_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_gly_j_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_gly_j_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_triso_1_j_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_triso_1_j_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_triso_2_j_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='gross_triso_2_j_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
