# Generated by Django 3.0.8 on 2022-01-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_auto_20220120_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='prix_pec',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
