# Generated by Django 3.0.8 on 2022-01-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_auto_20220128_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='listechoix',
            name='normale',
            field=models.BooleanField(default=False),
        ),
    ]
