# Generated by Django 4.0.6 on 2026-03-16 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0204_remove_admission_core_admission_patient_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='ae_title',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SuperAdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
