# Generated by Django 4.0.6 on 2026-04-22 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0214_add_categorie_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaveformConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_instance_uid', models.CharField(blank=True, max_length=64, null=True)),
                ('waveform_data', models.BinaryField(blank=True, null=True)),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='waveforms/previews/')),
                ('modality', models.CharField(default='WF', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waveforms', to='core.consultation')),
            ],
            options={
                'verbose_name': 'Waveform',
                'verbose_name_plural': 'Waveforms',
                'ordering': ['-created_at'],
            },
        ),
    ]
