[program:echo-store]
command = /home/echo/deploy/run.sh /home/echo/venv/bin/python /home/echo/echo/store.py
directory = /home/echo/echo
user = echo
autostart = true
autorestart = true
startretries = 3
environment = DJANGO_SETTINGS_MODULE="echo.settings.production",DISABLE_DICOM_AUTO=1
stdout_logfile = /home/echo/deploy/logs/echo-store.log
stderr_logfile = /home/echo/deploy/logs/echo-store-error.log
redirect_stderr = false
