[program:echo-store]
command = /var/www/echo/deploy/run.sh /var/www/echo/venv/bin/python /var/www/echo/echo/store.py
directory = /var/www/echo
user = root
autostart = true
autorestart = true
startretries = 3
environment = DJANGO_SETTINGS_MODULE="echo.settings.production",DISABLE_DICOM_AUTO=1
stdout_logfile = /var/www/echo/logs/echo-store.log
stderr_logfile = /var/www/echo/logs/echo-store-error.log
redirect_stderr = false
