[program:echo-gunicorn]
command=/var/www/echo/venv/bin/gunicorn echo.wsgi:application --bind 127.0.0.1:8000 --workers 3 --timeout 120
directory=/var/www/echo
user=root
autostart=true
autorestart=true
stderr_logfile=/var/www/echo/logs/gunicorn.err.log
stdout_logfile=/var/www/echo/logs/gunicorn.out.log
environment=DJANGO_SETTINGS_MODULE="echo.settings.production"
