# Generated by Django 3.0.8 on 2020-07-18 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('debut_consultation', models.DateTimeField(blank=True, null=True)),
                ('ordre', models.PositiveSmallIntegerField()),
                ('statut', models.CharField(choices=[(1, 'En attente'), (2, 'En consultation'), (3, 'Consultation terminée'), (10, 'Annulé')], default=1, max_length=2)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
            ],
        ),
    ]
