# Generated by Django 3.0.8 on 2020-09-08 13:05

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200902_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.models.Compte.storage_path),
        ),
        migrations.AddField(
            model_name='parametrescompte',
            name='nom_entete',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
