# Generated by Django 3.0.8 on 2020-10-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20200927_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestation', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('prix_ttc', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
