# Generated by Django 3.0.8 on 2020-11-06 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201031_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='Admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Admission'),
        ),
    ]
