# Generated by Django 3.0.8 on 2020-10-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20201029_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='forme',
            field=models.CharField(choices=[('comprime', 'Comprimé'), ('gelule', 'Gélule'), ('injection', 'Injection'), ('pommade', 'Pommade'), ('sirop', 'Sirop'), ('suppositoire', 'Suppositoire')], default='comprime', max_length=256),
            preserve_default=False,
        ),
    ]
