# Generated by Django 3.0.8 on 2020-11-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_listechoix'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentObstetrique',
            fields=[
                ('antecedent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Antecedent')),
                ('nb_foetus', models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], max_length=1)),
                ('date_accouchement', models.DateField(blank=True)),
                ('sexe', models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin'), ('I', 'Inconnu')], max_length=1)),
                ('prenom', models.CharField(blank=True, max_length=256, null=True)),
                ('poids_naissance', models.FloatField(blank=True)),
                ('allaitement', models.BooleanField(blank=True)),
                ('atcd_surligner', models.CharField(blank=True, max_length=256, null=True)),
                ('analgesie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analgesie', to='core.ListeChoix')),
                ('etat_sante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etat_sante', to='core.ListeChoix')),
                ('grossesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grossesse', to='core.ListeChoix')),
                ('indications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indications', to='core.ListeChoix')),
                ('lieu_accouchement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Etablissement')),
                ('mise_en_travail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mise_en_travail', to='core.ListeChoix')),
                ('perinee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perinee', to='core.ListeChoix')),
                ('suite_couche_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite_couche_detail', to='core.ListeChoix')),
                ('suite_couche_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite_couche_type', to='core.ListeChoix')),
                ('terme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terme', to='core.ListeChoix')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.antecedent',),
        ),
    ]
