# Generated by Django 3.0.8 on 2020-11-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20201103_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentobstetrique',
            name='atcd_surligner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
