# Generated by Django 3.0.8 on 2020-11-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20201104_0037'),
        ('core', '0026_auto_20201114_2358'),
    ]

    operations = [
    ]
