# Generated by Django 3.0.8 on 2020-12-13 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20201124_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
