# Generated by Django 3.0.8 on 2021-01-03 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20201230_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneesfoetus',
            name='doppler_cordon_diastole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doppler_cordon_diastole', to='core.ListeChoix'),
        ),
        migrations.AlterField(
            model_name='donneesfoetus',
            name='doppler_dv_onde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doppler_dv_onde', to='core.ListeChoix'),
        ),
    ]
