# Generated by Django 3.0.8 on 2021-01-19 22:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_merge_20210112_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationechopelvienne',
            name='adenomyose',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
