# Generated by Django 3.0.8 on 2021-02-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_antecedentobstetrique_evacuation_grossesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='ajouter_entetes_edition',
            field=models.BooleanField(default=True),
        ),
    ]
