# Generated by Django 3.0.8 on 2021-02-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_compte_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='antecedents_cardio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
