# Generated by Django 3.0.8 on 2021-03-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_listechoix_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationgynecologique',
            name='age_menarche',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='age_premier_rapport',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='bouffees_chaleur',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationgynecologique',
            name='presence_rapports_sexuels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_rapports_sexuels', to='core.ListeChoix'),
        ),
    ]
