# Generated by Django 3.0.8 on 2021-05-06 10:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_auto_20210506_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeordonnance',
            name='modele',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
