# Generated by Django 3.0.8 on 2021-06-01 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_auto_20210601_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentobstetrique',
            name='issue_grossesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_grossesse', to='core.ListeChoix'),
        ),
    ]
