# Generated by Django 3.0.8 on 2021-07-13 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_absencemedecin_praticien_remplacant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencemedecin',
            name='praticien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecin_principale', to='core.Medecin'),
        ),
        migrations.AlterField(
            model_name='absencemedecin',
            name='praticien_remplacant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecin_remplacant', to='core.Medecin'),
        ),
    ]
