# Generated by Django 3.0.8 on 2021-06-23 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_mesurespatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesurespatient',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
