# Generated by Django 3.0.8 on 2021-06-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_auto_20210627_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consanguinite_conjoint',
            field=models.CharField(blank=True, choices=[('', ''), ('oui', 'Oui'), ('non', 'Non')], default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_naissance_conjoint',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='etat_sante_conjoint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='groupe_sanguin_conjoint',
            field=models.CharField(blank=True, choices=[('A-', 'A négatif'), ('A+', 'A positif'), ('B-', 'B négatif'), ('B+', 'B positif'), ('AB-', 'AB négatif'), ('AB+', 'AB positif'), ('O-', 'O négatif'), ('O+', 'O positif')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nom_conjoint',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='prenom_conjoint',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='telephone_conjoint',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
