# Generated by Django 3.0.8 on 2021-10-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_auto_20210928_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='dpni_comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='type',
            field=models.CharField(choices=[('certificat_medical', 'Certificat médical'), ('certificat_presence', 'Certificat médical de présence'), ('lettre_accouchement', "Lettre d'accouchement"), ('lettre_confidentielle', 'Lettre confidentielle')], default='certificat_medical', max_length=128),
        ),
    ]
