# Generated by Django 3.0.8 on 2021-10-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_auto_20211010_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='test_t21_fait',
            field=models.BooleanField(default=False),
        ),
    ]
