# Generated by Django 3.0.8 on 2021-10-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_auto_20211023_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificat',
            name='type',
            field=models.CharField(choices=[('certificat_medical', 'Certificat médical'), ('certificat_presence', 'Certificat médical de présence'), ('lettre_accouchement', "Lettre d'accouchement"), ('lettre_confidentielle', 'Lettre confidentielle'), ('attestation_grossesse', 'Attestation de grossesse'), ('lettre_fittofly', 'Lettre Fit-To-Fly')], default='certificat_medical', max_length=128),
        ),
        migrations.AlterField(
            model_name='consultationgynecologique',
            name='tv',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='consultationobstetrique',
            name='tv',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
