# Generated by Django 3.0.8 on 2022-01-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_donneesfoetus_poids'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateedition',
            name='motif_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motif_consultation', to='core.MotifConsultation'),
        ),
    ]
