# Generated by Django 3.0.8 on 2022-02-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_donneesfoetus_morpho_liquide_amnio'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescompte',
            name='ajouter_date_cro',
            field=models.BooleanField(default=True),
        ),
    ]
